name = "brendanmckenzie-website"
main = "build/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration
[assets]
directory = "./public"
binding = "ASSETS"

# Environment variables should be set via: wrangler secret put <KEY>
# Required variables:
# - POK_ENVIRONMENT
# - POK_PROJECT
# - POK_TOKEN
# - POK_TOKEN_PREVIEW
