name = "brendanmckenzie-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

[env.production]
name = "brendanmckenzie-website"
routes = [
  { pattern = "brendan.mckenzie.io", custom_domain = true }
]

[env.production.vars]
# Environment will be set via wrangler secret put command:
# wrangler secret put POK_ENVIRONMENT
# wrangler secret put POK_PROJECT
# wrangler secret put POK_TOKEN
# wrangler secret put POK_TOKEN_PREVIEW
