name = "brendanmckenzie-website"
main = "public/_worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# For Cloudflare Pages deployment via GitHub:
# - Build command: npm run build
# - Build output directory: public
# - Environment variables configured in dashboard

# Required environment variables in Cloudflare dashboard:
# - POK_ENVIRONMENT
# - POK_PROJECT
# - POK_TOKEN
# - POK_TOKEN_PREVIEW
