name = "brendanmckenzie-website"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# For GitHub deployment: The Worker code is at public/_worker.js
# Static assets are served from public/ directory
# Environment variables are configured in the Cloudflare dashboard

# Required environment variables in Cloudflare dashboard:
# - POK_ENVIRONMENT
# - POK_PROJECT
# - POK_TOKEN
# - POK_TOKEN_PREVIEW
