name = "brendanmckenzie-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

# Environment variables should be set in Cloudflare Pages dashboard
# or via: wrangler pages secret put <KEY> --project-name=brendanmckenzie-website
# Required variables:
# - POK_ENVIRONMENT
# - POK_PROJECT
# - POK_TOKEN
# - POK_TOKEN_PREVIEW
